[package]
name = "openethereum_cli"
version = "0.1.0"
authors = ["wesrer"]
edition = "2018"

[dependencies]
structopt = { version = "~0.3" }
toml="0.5.6"
serde="~1.0"
serde_derive="~1.0"
rust-embed="5.5.1"
