[operating]
mode                        = "last"
mode_timeout                = "300"
mode_alarm                  = "3600"
auto_update                 = "critical"
auto_update_delay           = "100"
auto_update_check_frequency = "20"
release_track               = "current"
chain                       = "foundation" 
keys_path                   = "$BASE/keys"
identity                    = ""

[convenience]
config                      = "$BASE/config.toml"
ports_shift                 = "0" 

[account]
keys_iteration              = "10240"
accounts_refresh            = "5"

[private_transactions]

[ui_options]
ui_path                     = "$BASE/signer",

[networking]
port                        = "30303",
interface                   = "all",
snapshot_peers              = "0",
nat                         = "any",
allow_ips                   = "all",
max_pending_peers           = "64",

[ipc]
ipc_chmod                   = "660",
ipc_apis                    = "web3,eth,pubsub,net,parity,parity_pubsub,parity_accounts,private,traces,rpc,parity_transactions_pool",

[http_json_rpc]
jsonrpc_port                = "8545",
jsonrpc_interface           = "local",
jsonrpc_apis                = "web3,eth,pubsub,net,parity,private,parity_pubsub,traces,rpc,parity_transactions_pool",
jsonrpc_hosts               = "none",
jsonrpc_server_threads      = "4",
jsonrpc_cors                = "none",
poll_lifetime               = "60",

[light_client]

[websockets]
ws_port = "8546",
ws_interface = "local",
ws_apis = "web3,eth,pubsub,net,parity,parity_pubsub,private,traces,rpc,parity_transactions_pool",
ws_origins = "parity://*,chrome-extension://*,moz-extension://*",
ws_hosts = "none",
ws_max_connections = "100",

[secret_store]
secretstore_http_cors = "none"
secretstore_acl_contract = "registry",
secretstore_nodes = ""
secretstore_server_set_contract = "registry",
secretstore_interface = "local"
secretstore_port = "8083",
secretstore_http_interface = "local",
secretstore_http_port = "8082",
secretstore_path = "$BASE/secretstore",

[sealing_mining]
reseal_on_txs = "own",
reseal_min_period = "2000"
reseal_max_period = "120000",
work_queue_size = "20",
relay_set = "cheap",
usd_per_tx = "0.0001",
usd_per_eth = "auto",
price_update_period = "hourly",
gas_floor_target = "8000000",
gas_cap = "10000000",
tx_queue_mem_limit = "4",
tx_queue_size = "8192",
tx_queue_strategy = "gas_price",
stratum_interface = "local",
stratum_port = "8008",
gas_price_percentile = "50",
max_round_blocks_to_import = "12",
        
[internal]

[miscellaneous]

[footprint]
tracing = "auto"
pruning = "auto",
pruning_history = "128",
pruning_memory = "64"
cache_size_db = "128",
cache_size_blocks = "8"
cache_size_queue = "40"
cache_size_state = "25"
db_compaction = "auto",
fat_db = "auto",

[import_export]

[snapshot]

[legacy]

